In [8]:
#logistic algorthim
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [10]:
dataset = pd.read_csv("pregnancy_Nutrition.csv")

In [11]:
dataset

     Age   BMI  Hemoglobin  BloodPressure  SugarLevel  ProteinIntake    Risk
0     24  26.8        12.3            106         168             62    High
1     37  29.1        12.1            132          89             67     Low
2     32  25.0        13.0            148         130             37    High
3     28  26.1        13.0            140         175             40    High
4     25  24.9        10.8            143         104             51    High
..   ...   ...         ...            ...         ...            ...     ...
295   23  29.7        10.7             94         107             66     Low
296   30  24.6        12.6            143         101             44    High
297   36  23.8         9.7            136          80             65  Medium
298   39  21.8         9.7            138         114             44  Medium
299   25  18.8        11.7             98         158             52    High

[300 rows x 7 columns]

In [12]:
le = LabelEncoder()
dataset["Risk"] = le.fit_transform(dataset["Risk"])

In [13]:
dataset = pd.get_dummies(dataset, drop_first=True)

In [14]:
independent = dataset[["Age","BMI","Hemoglobin","BloodPressure","SugarLevel","ProteinIntake"]]

In [15]:
independent

     Age   BMI  Hemoglobin  BloodPressure  SugarLevel  ProteinIntake
0     24  26.8        12.3            106         168             62
1     37  29.1        12.1            132          89             67
2     32  25.0        13.0            148         130             37
3     28  26.1        13.0            140         175             40
4     25  24.9        10.8            143         104             51
..   ...   ...         ...            ...         ...            ...
295   23  29.7        10.7             94         107             66
296   30  24.6        12.6            143         101             44
297   36  23.8         9.7            136          80             65
298   39  21.8         9.7            138         114             44
299   25  18.8        11.7             98         158             52

[300 rows x 6 columns]

In [16]:
dependent = dataset["Risk"]

In [17]:
dependent

0      0
1      1
2      0
3      0
4      0
      ..
295    1
296    0
297    2
298    2
299    0
Name: Risk, Length: 300, dtype: int64

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [19]:
# creating logistic Algorithm Classification Model

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)

C:\Users\premchandar\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(random_state=0)

In [20]:
y_pred = classifier.predict(x_test)
y_pred

array([1, 0, 0, 0, 0, 0, 2, 1, 2, 0, 0, 0, 0, 2, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 2, 1, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 1, 1, 0, 0, 2, 0, 2, 0, 0,
       2, 0, 1, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0,
       0, 0, 0, 2, 1, 2, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 2, 0, 0, 0, 0, 1, 0, 1, 1])

In [21]:
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_test,y_pred)
conf_matrix

array([[53,  2,  4],
       [ 1, 18,  3],
       [12,  1,  6]])

In [22]:
from sklearn.metrics import classification_report
class_report = classification_report(y_test,y_pred)
print(class_report)

              precision    recall  f1-score   support

           0       0.80      0.90      0.85        59
           1       0.86      0.82      0.84        22
           2       0.46      0.32      0.38        19

    accuracy                           0.77       100
   macro avg       0.71      0.68      0.69       100
weighted avg       0.75      0.77      0.76       100

In [32]:
#random forest
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [34]:
dataset = pd.read_csv("pregnancy_Nutrition.csv")

In [35]:
dataset

     Age   BMI  Hemoglobin  BloodPressure  SugarLevel  ProteinIntake    Risk
0     24  26.8        12.3            106         168             62    High
1     37  29.1        12.1            132          89             67     Low
2     32  25.0        13.0            148         130             37    High
3     28  26.1        13.0            140         175             40    High
4     25  24.9        10.8            143         104             51    High
..   ...   ...         ...            ...         ...            ...     ...
295   23  29.7        10.7             94         107             66     Low
296   30  24.6        12.6            143         101             44    High
297   36  23.8         9.7            136          80             65  Medium
298   39  21.8         9.7            138         114             44  Medium
299   25  18.8        11.7             98         158             52    High

[300 rows x 7 columns]

In [36]:
le = LabelEncoder()
dataset["Risk"] = le.fit_transform(dataset["Risk"])

In [37]:
X = dataset.drop("Risk", axis=1)
X = pd.get_dummies(X, drop_first=True)

In [38]:
y = dataset["Risk"]

In [39]:
independent = dataset[["Age","BMI","Hemoglobin","BloodPressure","SugarLevel","ProteinIntake"]]

In [40]:
independent

     Age   BMI  Hemoglobin  BloodPressure  SugarLevel  ProteinIntake
0     24  26.8        12.3            106         168             62
1     37  29.1        12.1            132          89             67
2     32  25.0        13.0            148         130             37
3     28  26.1        13.0            140         175             40
4     25  24.9        10.8            143         104             51
..   ...   ...         ...            ...         ...            ...
295   23  29.7        10.7             94         107             66
296   30  24.6        12.6            143         101             44
297   36  23.8         9.7            136          80             65
298   39  21.8         9.7            138         114             44
299   25  18.8        11.7             98         158             52

[300 rows x 6 columns]

In [41]:
dependent = dataset["Risk"]

In [42]:
dependent

0      0
1      1
2      0
3      0
4      0
      ..
295    1
296    0
297    2
298    2
299    0
Name: Risk, Length: 300, dtype: int64

In [43]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [45]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [46]:
y_pred = classifier.predict(x_test)

In [47]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [48]:
print(cm)

[[57  0  2]
 [ 0 22  0]
 [ 1  0 18]]

In [49]:
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)

In [50]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.98      0.97      0.97        59
           1       1.00      1.00      1.00        22
           2       0.90      0.95      0.92        19

    accuracy                           0.97       100
   macro avg       0.96      0.97      0.97       100
weighted avg       0.97      0.97      0.97       100

In [51]:
#decision tree
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [52]:
dataset = pd.read_csv("pregnancy_Nutrition.csv")

In [53]:
dataset

     Age   BMI  Hemoglobin  BloodPressure  SugarLevel  ProteinIntake    Risk
0     24  26.8        12.3            106         168             62    High
1     37  29.1        12.1            132          89             67     Low
2     32  25.0        13.0            148         130             37    High
3     28  26.1        13.0            140         175             40    High
4     25  24.9        10.8            143         104             51    High
..   ...   ...         ...            ...         ...            ...     ...
295   23  29.7        10.7             94         107             66     Low
296   30  24.6        12.6            143         101             44    High
297   36  23.8         9.7            136          80             65  Medium
298   39  21.8         9.7            138         114             44  Medium
299   25  18.8        11.7             98         158             52    High

[300 rows x 7 columns]

In [54]:
le = LabelEncoder()
dataset["Risk"] = le.fit_transform(dataset["Risk"])

In [55]:
dataset = pd.get_dummies(dataset, drop_first=True)

In [56]:
independent = dataset[["Age","BMI","Hemoglobin","BloodPressure","SugarLevel","ProteinIntake"]]

In [57]:
independent

     Age   BMI  Hemoglobin  BloodPressure  SugarLevel  ProteinIntake
0     24  26.8        12.3            106         168             62
1     37  29.1        12.1            132          89             67
2     32  25.0        13.0            148         130             37
3     28  26.1        13.0            140         175             40
4     25  24.9        10.8            143         104             51
..   ...   ...         ...            ...         ...            ...
295   23  29.7        10.7             94         107             66
296   30  24.6        12.6            143         101             44
297   36  23.8         9.7            136          80             65
298   39  21.8         9.7            138         114             44
299   25  18.8        11.7             98         158             52

[300 rows x 6 columns]

In [58]:
dependent = dataset["Risk"]

In [59]:
dependent

0      0
1      1
2      0
3      0
4      0
      ..
295    1
296    0
297    2
298    2
299    0
Name: Risk, Length: 300, dtype: int64

In [60]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [61]:
# Create Decision Tree Classifier Model

from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [62]:
y_pred = classifier.predict(x_test)
y_pred

array([1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 2, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 2, 1, 1, 0, 0, 2, 2, 2, 0, 0,
       2, 0, 1, 2, 2, 1, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0,
       2, 0, 0, 2, 1, 1, 0, 0, 0, 2, 2, 0, 0, 0, 2, 0, 2, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 2, 1, 1])

In [63]:
from sklearn.metrics import confusion_matrix
conf_matrix= confusion_matrix(y_test,y_pred)
print(conf_matrix)

[[57  0  2]
 [ 0 22  0]
 [ 1  1 17]]

In [64]:
from sklearn.metrics import classification_report
class_report = classification_report(y_test,y_pred)
print(class_report)

              precision    recall  f1-score   support

           0       0.98      0.97      0.97        59
           1       0.96      1.00      0.98        22
           2       0.89      0.89      0.89        19

    accuracy                           0.96       100
   macro avg       0.94      0.95      0.95       100
weighted avg       0.96      0.96      0.96       100

In [1]:
#knn 
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
dataset = pd.read_csv("pregnancy_Nutrition.csv")

In [3]:
dataset

     Age   BMI  Hemoglobin  BloodPressure  SugarLevel  ProteinIntake    Risk
0     24  26.8        12.3            106         168             62    High
1     37  29.1        12.1            132          89             67     Low
2     32  25.0        13.0            148         130             37    High
3     28  26.1        13.0            140         175             40    High
4     25  24.9        10.8            143         104             51    High
..   ...   ...         ...            ...         ...            ...     ...
295   23  29.7        10.7             94         107             66     Low
296   30  24.6        12.6            143         101             44    High
297   36  23.8         9.7            136          80             65  Medium
298   39  21.8         9.7            138         114             44  Medium
299   25  18.8        11.7             98         158             52    High

[300 rows x 7 columns]

In [4]:
le = LabelEncoder()
dataset["Risk"] = le.fit_transform(dataset["Risk"])

In [5]:
dataset = pd.get_dummies(dataset, drop_first=True)

In [6]:
independent = dataset[["Age","BMI","Hemoglobin","BloodPressure","SugarLevel","ProteinIntake"]]

In [7]:
independent

     Age   BMI  Hemoglobin  BloodPressure  SugarLevel  ProteinIntake
0     24  26.8        12.3            106         168             62
1     37  29.1        12.1            132          89             67
2     32  25.0        13.0            148         130             37
3     28  26.1        13.0            140         175             40
4     25  24.9        10.8            143         104             51
..   ...   ...         ...            ...         ...            ...
295   23  29.7        10.7             94         107             66
296   30  24.6        12.6            143         101             44
297   36  23.8         9.7            136          80             65
298   39  21.8         9.7            138         114             44
299   25  18.8        11.7             98         158             52

[300 rows x 6 columns]

In [8]:
dependent = dataset["Risk"]

In [9]:
dependent

0      0
1      1
2      0
3      0
4      0
      ..
295    1
296    0
297    2
298    2
299    0
Name: Risk, Length: 300, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [11]:
# creating K Near-Neighbour classification model

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=7,metric='minkowski',p=2)
classifier.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=7)

In [12]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 2, 0, 2, 0, 1, 0, 1, 0, 0, 0, 2, 0, 1, 2, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 2, 0, 0, 2, 0, 0, 2, 2, 0, 0, 2, 0, 0, 0,
       2, 0, 0, 2, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1])

In [13]:
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_test,y_pred)
conf_matrix

array([[53,  1,  5],
       [ 8, 12,  2],
       [ 9,  2,  8]])

In [14]:
from sklearn.metrics import classification_report
class_report = classification_report(y_test,y_pred)
print(class_report)

              precision    recall  f1-score   support

           0       0.76      0.90      0.82        59
           1       0.80      0.55      0.65        22
           2       0.53      0.42      0.47        19

    accuracy                           0.73       100
   macro avg       0.70      0.62      0.65       100
weighted avg       0.72      0.73      0.72       100

In [15]:
#navies bayes
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [16]:
dataset = pd.read_csv("pregnancy_Nutrition.csv")

In [17]:
dataset

     Age   BMI  Hemoglobin  BloodPressure  SugarLevel  ProteinIntake    Risk
0     24  26.8        12.3            106         168             62    High
1     37  29.1        12.1            132          89             67     Low
2     32  25.0        13.0            148         130             37    High
3     28  26.1        13.0            140         175             40    High
4     25  24.9        10.8            143         104             51    High
..   ...   ...         ...            ...         ...            ...     ...
295   23  29.7        10.7             94         107             66     Low
296   30  24.6        12.6            143         101             44    High
297   36  23.8         9.7            136          80             65  Medium
298   39  21.8         9.7            138         114             44  Medium
299   25  18.8        11.7             98         158             52    High

[300 rows x 7 columns]

In [18]:
le = LabelEncoder()
dataset["Risk"] = le.fit_transform(dataset["Risk"])

In [19]:
dataset = pd.get_dummies(dataset, drop_first=True)

In [20]:
independent = dataset[["Age","BMI","Hemoglobin","BloodPressure","SugarLevel","ProteinIntake"]]

In [21]:
independent

     Age   BMI  Hemoglobin  BloodPressure  SugarLevel  ProteinIntake
0     24  26.8        12.3            106         168             62
1     37  29.1        12.1            132          89             67
2     32  25.0        13.0            148         130             37
3     28  26.1        13.0            140         175             40
4     25  24.9        10.8            143         104             51
..   ...   ...         ...            ...         ...            ...
295   23  29.7        10.7             94         107             66
296   30  24.6        12.6            143         101             44
297   36  23.8         9.7            136          80             65
298   39  21.8         9.7            138         114             44
299   25  18.8        11.7             98         158             52

[300 rows x 6 columns]

In [22]:
dependent = dataset["Risk"]

In [23]:
dependent

0      0
1      1
2      0
3      0
4      0
      ..
295    1
296    0
297    2
298    2
299    0
Name: Risk, Length: 300, dtype: int64

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [25]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)

In [26]:
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_test,y_pred)
print(conf_matrix)

[[59  0  0]
 [ 3 17  2]
 [13  0  6]]

In [27]:
# find and print Classification_Repot

from sklearn.metrics import classification_report
class_report = classification_report(y_test, y_pred)
print(class_report)

              precision    recall  f1-score   support

           0       0.79      1.00      0.88        59
           1       1.00      0.77      0.87        22
           2       0.75      0.32      0.44        19

    accuracy                           0.82       100
   macro avg       0.85      0.70      0.73       100
weighted avg       0.83      0.82      0.80       100

In [28]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)

# confusion Matrix
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_test,y_pred)
# print(conf_matrix)

# find and print Classification_Repot
from sklearn.metrics import classification_report
class_report = classification_report(y_test, y_pred)
print(class_report)
print(conf_matrix)

              precision    recall  f1-score   support

           0       0.73      0.76      0.74        59
           1       0.56      0.82      0.67        22
           2       0.50      0.16      0.24        19

    accuracy                           0.66       100
   macro avg       0.60      0.58      0.55       100
weighted avg       0.65      0.66      0.63       100

[[45 13  1]
 [ 2 18  2]
 [15  1  3]]

In [29]:
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)

# confusion Matrix
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_test,y_pred)
# print(conf_matrix)

# find and print Classification_Repot
from sklearn.metrics import classification_report
class_report = classification_report(y_test, y_pred)
print(class_report)
print(conf_matrix)

              precision    recall  f1-score   support

           0       0.59      1.00      0.74        59
           1       0.00      0.00      0.00        22
           2       0.00      0.00      0.00        19

    accuracy                           0.59       100
   macro avg       0.20      0.33      0.25       100
weighted avg       0.35      0.59      0.44       100

[[59  0  0]
 [22  0  0]
 [19  0  0]]

C:\Users\premchandar\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\premchandar\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\premchandar\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [31]:
#SVM
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [32]:
dataset = pd.read_csv("pregnancy_Nutrition.csv")

In [33]:
dataset

     Age   BMI  Hemoglobin  BloodPressure  SugarLevel  ProteinIntake    Risk
0     24  26.8        12.3            106         168             62    High
1     37  29.1        12.1            132          89             67     Low
2     32  25.0        13.0            148         130             37    High
3     28  26.1        13.0            140         175             40    High
4     25  24.9        10.8            143         104             51    High
..   ...   ...         ...            ...         ...            ...     ...
295   23  29.7        10.7             94         107             66     Low
296   30  24.6        12.6            143         101             44    High
297   36  23.8         9.7            136          80             65  Medium
298   39  21.8         9.7            138         114             44  Medium
299   25  18.8        11.7             98         158             52    High

[300 rows x 7 columns]

In [34]:
le = LabelEncoder()
dataset["Risk"] = le.fit_transform(dataset["Risk"])

In [35]:
dataset = pd.get_dummies(dataset, drop_first=True)

In [36]:
independent = dataset[["Age","BMI","Hemoglobin","BloodPressure","SugarLevel","ProteinIntake"]]

In [37]:
independent

     Age   BMI  Hemoglobin  BloodPressure  SugarLevel  ProteinIntake
0     24  26.8        12.3            106         168             62
1     37  29.1        12.1            132          89             67
2     32  25.0        13.0            148         130             37
3     28  26.1        13.0            140         175             40
4     25  24.9        10.8            143         104             51
..   ...   ...         ...            ...         ...            ...
295   23  29.7        10.7             94         107             66
296   30  24.6        12.6            143         101             44
297   36  23.8         9.7            136          80             65
298   39  21.8         9.7            138         114             44
299   25  18.8        11.7             98         158             52

[300 rows x 6 columns]

In [38]:
dependent = dataset["Risk"]

In [39]:
dependent

0      0
1      1
2      0
3      0
4      0
      ..
295    1
296    0
297    2
298    2
299    0
Name: Risk, Length: 300, dtype: int64

In [40]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [41]:
# Creating SVM Classifier Model

from sklearn.svm import SVC
classifier =  SVC(kernel='rbf', random_state=0)
classifier =  classifier.fit(x_train,y_train)
classifier

SVC(random_state=0)

In [42]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_test,y_pred)
conf_matrix

array([[59,  0,  0],
       [22,  0,  0],
       [19,  0,  0]])

In [44]:
from sklearn.metrics import classification_report
class_report = classification_report(y_test,y_pred)
print(class_report)

              precision    recall  f1-score   support

           0       0.59      1.00      0.74        59
           1       0.00      0.00      0.00        22
           2       0.00      0.00      0.00        19

    accuracy                           0.59       100
   macro avg       0.20      0.33      0.25       100
weighted avg       0.35      0.59      0.44       100

C:\Users\premchandar\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\premchandar\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\premchandar\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])